language: java
install: true

jdk:
  - openjdk11

script:
  - ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - nvm install 10.12.0
  - nvm use 10.12.0